### ISSUE TITLE
invalid conversion from 'void*' to 'lv_obj_t* {aka _lv_obj_t*}' [-fpermissive]

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [CasaVinteUm/Cafe21#5]
void configPasswordKeyboardValueChanged(lv_event_t *e)
{
  lv_event_code_t code = lv_event_get_code(e);

  // lv_obj_t *obj = lv_event_get_target(e);
  // https://github.com/lvgl/lvgl/issues/3542
  // https://forum.lvgl.io/t/lv-event-get-user-data-gives-invalid-conversion-error/9975/3
  
  lv_obj_t * obj = (lv_obj_t*) lv_event_get_user_data(e); //<------------------------no error now!

**Comment by nGoline** [comment]
I don't get any error on my end. Can you provide more data on this error and/or reproducing steps?

**Comment by andersondeoliveiramachado** [comment]
![image](https://github.com/user-attachments/assets/0bbbbc48-4532-469d-8548-48218e55b3e2)
![image](https://github.com/user-attachments/assets/4d23148a-5420-4914-9138-6bdf8de2595b)

When platformio downloads the library https://github.com/rzeldent/esp32-smartdisplay , the version that comes in LVGL is 9.2.2 , and the project has lv_cof.h for version /**
* @file lv_conf.h
* Configuration file for v8.3.2
*/
What I did to solve it was to download lv_conf.h from the example: https://github.com/rzeldent/esp32-smartdisplay-demo/blob/main/include/lv_conf.h

The image files also need adjustments:

const lv_img_dsc_t ui_img_check_png = {
.header.always_zero = 0,
.header.w = 132,
.header.h = 132,
.data_size = sizeof(ui_img_check_png_data), .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .data = ui_img_check_png_data};

**Comment by nGoline** [comment]
OK, thank you for the report.

I was able to reproduce it by performing a fresh install of the repo (deleted the `.pio` folder), having lgvl 9.2.2 installed.
 
That's odd, since the dependency `rzeldent/esp32_smartdisplay@^2.0.11` explicitly depends on `lvgl/lvgl@^8.4.0`.

I'll investigate further and find a fix for it.

**Comment by nGoline** [comment]
I've found the issue!

We were requesting the library `resident/esp32_smartdisplay@2.0.11`. See the problem? The `^` (caret) means that we want any minor version **from** 2.0.11`, which is satisfied by `2.1.0`.

Furthermore, looking at the [diff between 2.0.11 and 2.1.0](https://github.com/rzeldent/esp32-smartdisplay/compare/2.0.11...2.1.0), one can say that the API has a breaking change, hence the need for a major bump in their version. It should have gone from `2.0.11` to `3.0.0` to reflect the `lv_conf` change, among other breaking changes.

For now, I'm removing the caret and fixing our dependency on `rzeldent/esp32_smartdisplay@2.0.11`.

Do you mind testing the new code (#7) and reporting back so we can merge it?

**Comment by nGoline** [comment]
@andersondeoliveiramachado I've just opened #8 asking for help on upgrading `resident/esp32_smartdisplay` to latest. Do you think you could help us?

**Comment by andersondeoliveiramachado** [comment]
> I've found the issue!
> 
> We were requesting the library `resident/esp32_smartdisplay@2.0.11`. See the problem? The `^` (caret) means that we want any minor version **from** 2.0.11`, which is satisfied by `2.1.0`.
> 
> Furthermore, looking at the [diff between 2.0.11 and 2.1.0](https://github.com/rzeldent/esp32-smartdisplay/compare/2.0.11...2.1.0), one can say that the API has a breaking change, hence the need for a major bump in their version. It should have gone from `2.0.11` to `3.0.0` to reflect the `lv_conf` change, among other breaking changes.
> 
> For now, I'm removing the caret and fixing our dependency on `rzeldent/esp32_smartdisplay@2.0.11`.
> 
> Do you mind testing the new code (#7) and reporting back so we can merge it?

It compiled without any problems. I just had to add the board I have here (esp32-8048S070C) to platformio.ini
`
[platformio]
default_envs = esp32-8048S070C

[env:esp32-8048S070C]
board = esp32-8048S070C
lib_deps =
	bblanchon/ArduinoJson@^6.21.2
	https://github.com/tzapu/WiFiManager.git
	links2004/WebSockets@^2.4.1
    rzeldent/esp32_smartdisplay@2.0.11
build_flags =
	${env.build_flags}
build_src_filter = +<*> -<fakeCoffeeMachine/>
lib_ignore =
	ui_320
	ui_480

`

![image](https://github.com/user-attachments/assets/4cb0cd0e-29f0-41ce-8b18-0ca12cb730e8)

**Comment by nGoline** [comment]
Glad it worked!

**Comment by andersondeoliveiramachado** [comment]
> @andersondeoliveiramachado I've just opened #8 asking for help on upgrading `resident/esp32_smartdisplay` to latest. Do you think you could help us?



> @andersondeoliveiramachado I've just opened #8 asking for help on upgrading `resident/esp32_smartdisplay` to latest. Do you think you could help us?



> @andersondeoliveiramachado I've just opened #8 asking for help on upgrading `resident/esp32_smartdisplay` to latest. Do you think you could help us?

I managed to compile a version for https://github.com/rzeldent/esp32-smartdisplay that uses the LVGL 9.2.2 library, basically what I did was put the lv_conf.h from the project https://github.com/rzeldent/esp32-smartdisplay-demo/blob/main/include/lv_conf.h in place of Cafe21\include\lv_conf.h and modified the image files, which I believe SquareLine Studio Boards create accordingly for LVGL 9.

In the image files I modified it this way:

 From: 

`
const lv_img_dsc_t ui_img_check_png = {
   .header.always_zero = 0,
   .header.w = 132,
   .header.h = 132,
   .data_size = sizeof(ui_img_check_png_data),
   .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
   .data = ui_img_check_png_data};
`

For : 

`
const lv_img_dsc_t ui_img_check_png = {
   .header.w = 132,
   .header.h = 132,
   .data_size = sizeof(ui_img_check_png_data),
   .data = ui_img_check_png_data};
`
