### ISSUE TITLE
new qrcode syntax

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [CasaVinteUm/Cafe21#6]
`
void UIController::showQrCode(uint8_t buttonNumber, lv_coord_t size)
{
    // Create and update QR code
    log_d("Generating QRCode for button %d. %s", buttonNumber, buttonNumber == 1 ? lightningController.getButton1Lnurl() : lightningController.getButton2Lnurl());
    
    //auto ui_qrcode = lv_qrcode_create(ui_qrCodeContainer, size ? size : QRCODE_INITIAL_SIZE, lv_color_black(), lv_color_white());

    // nova sintaxe do qrcode no LVGL  v9.2.2
    auto ui_qrcode = lv_qrcode_create(ui_qrCodeContainer);
    lv_qrcode_set_size(ui_qrcode, QRCODE_INITIAL_SIZE);
    lv_qrcode_set_dark_color(ui_qrcode, lv_color_black());
    lv_qrcode_set_light_color(ui_qrcode, lv_color_white());    

    String qrData = buttonNumber == 1 ? lightningController.getButton1Lnurl() : lightningController.getButton2Lnurl();
    
    lv_qrcode_update(ui_qrcode, qrData.c_str(), qrData.length());
    lv_obj_center(ui_qrcode);
}

`

**Comment by nGoline** [comment]
We're using LGVL 8.4.0, which means the current implementation is correct.

**Comment by andersondeoliveiramachado** [comment]
When platformio downloads the library https://github.com/rzeldent/esp32-smartdisplay , the version that comes in LVGL is 9.2.2 , and the project has lv_cof.h for version v8.3.2
